### ISSUE TITLE
bigint support for version 2.3.6

### ISSUE THREAD

**Issue by ShowmanStone** [IBM/node-odbc#395]
hi，
i try to use node-odbc v2.3.6 as my node version is limited to v8.17.0, but i got some napi_bigint error when i run npm install, how can i fix this?

**Comment by kadler** [comment]
Unfortunately we have long since moved on from Node.js 8 and v2.3 of node-odbc. [This commit](https://github.com/IBM/node-odbc/commit/d9c630909f12b8a4c9bb1e9d82531ef6792cd08c) added conditional compilation for BigInt support. Maybe you can use a [github url dependency](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#github-urls) eg.

```json
  "dependencies": {
    "odbc": "IBM/odbc#d9c630909f12b8a4c9bb1e9d82531ef6792cd08c",
  }
```

I haven't actually used this support or tested this, though. It's as much help as we can provide. Good luck!
